//Teste de Requisições REST - Categorias
@baseURL = http://localhost:4000
@id = 609043ac602c7f03076304f5
###
// GET - Lista todas as categorias
GET {{baseURL}}/categorias
Content-Type: application/json

###
// GET - Lista apenas uma categoria pelo id
GET {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
// GET - Lista apenas uma categoria pelo id - INVÁLIDO
GET {{baseURL}}/categorias/44
Content-Type: application/json

###
// POST - Inclui uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{
    "nome": "Grand Theft Auto 5",
    "data": "12/09/1992",
    "genero": "Sandbox",
    "plataforma": "Steam",
    "tamanho": "78GB",
    "desenvolvedora": "Rockstar Games",
    "status": "ativo"
}

### 
// DELETE - Apaga uma categoria através do id informado
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
// PUT - Altera uma categoria pelo ID
PUT {{baseURL}}/categorias
Content-Type: application/json

{
    "_id": "6090376b1f4ecc016577707e", 
    "nome": "Grand Theft Auto 5",
    "data": "12/09/1992",
    "genero": "Sandbox",
    "plataforma": "Steam",
    "tamanho": "78GB",
    "desenvolvedora": "Rockstar Games",
    "status": "ativo"
}


###
// PUT - Altera uma categoria pelo ID - INVÁLIDO
PUT {{baseURL}}/categorias
Content-Type: application/json

{
    "_id": "9999", 
    "nome": "Grand Theft Auto 5",
    "data": "12/09/1992",
    "genero": "Sandbox",
    "plataforma": "Steam",
    "tamanho": "78GB",
    "desenvolvedora": "Rockstar Games",
    "status": "ativo"
}